<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    //'WdevPicture\Module'                        => __DIR__ . '/Module.php',
    //'WdevPicture\Controller\SkeletonController' => __DIR__ . '/src/WdevPicture/Controller/SkeletonController.php',
);