<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    //'wdev-picture\Module'                        => __DIR__ . '/Module.php',
    //'wdev-picture\Controller\SkeletonController' => __DIR__ . '/src/wdev-picture/Controller/SkeletonController.php',
);